source 'https://rubygems.org'

gem 'rspec'                  # Biblioteca de asserções
gem 'site_prism' 
gem 'selenium-webdriver'     # Controle do navegador
gem 'capybara'               # API para automação de navegação
gem 'parallel_tests'         # Execução paralela de testes(EX. Dois navegadores)
gem 'faker'                  # Geração de dados aleatórios (Ficiticios)
gem 'cucumber', '~> 7.0'

